name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  html-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install html-validate
        run: npm install -g html-validate
      - name: Validate HTML files
        run: html-validate "**/*.html"
